version: '2.3'
services:
  cudaenv:
    build:
      context: .
      dockerfile: Dockerfile_pytorch.dockerfile
      # dockerfile: Dockerfile_tensor.dockerfile
    runtime: nvidia
    network_mode: "host"  
    volumes:
      - "~/:/home"
    privileged: true
    command: jupyter lab --ip=0.0.0.0 --allow-root
